# Generated by Django 2.1.1 on 2018-09-23 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('korok', '0005_auto_20180923_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eszkoz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('expiration_date', models.DateField()),
                ('store_id', models.SlugField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korok.Hallgato')),
            ],
        ),
    ]
