# Generated by Django 2.1.1 on 2018-09-22 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hallgato',
            fields=[
                ('name', models.CharField(blank=True, max_length=50)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
                ('age', models.IntegerField()),
                ('neptun', models.SlugField(blank=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Kor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='korok.Hallgato')),
            ],
        ),
    ]
