# Generated by Django 2.1.1 on 2018-09-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korok', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kor',
            name='members',
            field=models.ManyToManyField(related_name='tagok', to='korok.Hallgato'),
        ),
    ]
