# Generated by Django 2.1.1 on 2018-09-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korok', '0005_auto_20180923_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hallgato',
            options={'ordering': ['age']},
        ),
    ]
